feat(pipeline): fail if no version was found

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -213,6 +213,10 @@ jobs:
         run: |
           REPO="RouHim/sensor-bridge"
           LATEST_RELEASE_VERSION=$(curl --silent "https://api.github.com/repos/$REPO/releases/latest" | jq -r ".tag_name")
+          if [ -z "$LATEST_RELEASE_VERSION" ]; then
+              echo "No release found, failing..."
+              exit 1
+          fi
           echo "Latest release is $LATEST_RELEASE_VERSION"
           echo "VERSION=$LATEST_RELEASE_VERSION" >> $GITHUB_ENV
 
